//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMX_Dataloader.Main {
    
    
    public partial class Profile {
        
        /// <summary>
        /// UserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SDMX_Dataloader.Main.Controls.UserControl UserControl;
        
        /// <summary>
        /// ManagerUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SDMX_Dataloader.Main.Controls.ManagerUserControl ManagerUserControl;
    }
}
