//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMX_Dataloader.Main.Controls {
    
    
    public partial class FileUploaderControl {
        
        /// <summary>
        /// CSVUploadControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SDMX_Dataloader.Main.Controls.CSVUploadControl CSVUploadControl;
        
        /// <summary>
        /// MultipleFileUploadControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SDMX_Dataloader.Main.Controls.MultipleFileUploadControl MultipleFileUploadControl;
    }
}
