//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18052
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        ///   le ricerche di risorse che utilizzano questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SDMX Dataloader ®2015 - ISTAT - National Institute of Statistics - Via Cesare Balbo 16 00184 - Roma tel. +39 06 46731.
        /// </summary>
        internal static string app_copy {
            get {
                return ResourceManager.GetString("app_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SDMX Dataloader.
        /// </summary>
        internal static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        internal static string lbl_add {
            get {
                return ResourceManager.GetString("lbl_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Description.
        /// </summary>
        internal static string lbl_add_desc {
            get {
                return ResourceManager.GetString("lbl_add_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add File.
        /// </summary>
        internal static string lbl_add_file {
            get {
                return ResourceManager.GetString("lbl_add_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Name.
        /// </summary>
        internal static string lbl_add_name {
            get {
                return ResourceManager.GetString("lbl_add_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Install.
        /// </summary>
        internal static string lbl_btn_install {
            get {
                return ResourceManager.GetString("lbl_btn_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Builder.
        /// </summary>
        internal static string lbl_builder {
            get {
                return ResourceManager.GetString("lbl_builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string lbl_cancel {
            get {
                return ResourceManager.GetString("lbl_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change production status.
        /// </summary>
        internal static string lbl_change_production {
            get {
                return ResourceManager.GetString("lbl_change_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Character to be replaced.
        /// </summary>
        internal static string lbl_char_change {
            get {
                return ResourceManager.GetString("lbl_char_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Concept.
        /// </summary>
        internal static string lbl_concept {
            get {
                return ResourceManager.GetString("lbl_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Concept dettail.
        /// </summary>
        internal static string lbl_concept_dettail {
            get {
                return ResourceManager.GetString("lbl_concept_dettail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm.
        /// </summary>
        internal static string lbl_confirm {
            get {
                return ResourceManager.GetString("lbl_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm request.
        /// </summary>
        internal static string lbl_confirm_request {
            get {
                return ResourceManager.GetString("lbl_confirm_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connection Status.
        /// </summary>
        internal static string lbl_connection_status {
            get {
                return ResourceManager.GetString("lbl_connection_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File content.
        /// </summary>
        internal static string lbl_content {
            get {
                return ResourceManager.GetString("lbl_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total record.
        /// </summary>
        internal static string lbl_countRows {
            get {
                return ResourceManager.GetString("lbl_countRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A Datacube will be created? Continue?.
        /// </summary>
        internal static string lbl_create_cube_confirm {
            get {
                return ResourceManager.GetString("lbl_create_cube_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create mapping.
        /// </summary>
        internal static string lbl_create_mapping {
            get {
                return ResourceManager.GetString("lbl_create_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A Mapping will be created? Continue?.
        /// </summary>
        internal static string lbl_create_mapping_confirm {
            get {
                return ResourceManager.GetString("lbl_create_mapping_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cube Details.
        /// </summary>
        internal static string lbl_cube_detail {
            get {
                return ResourceManager.GetString("lbl_cube_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Import.
        /// </summary>
        internal static string lbl_data_import {
            get {
                return ResourceManager.GetString("lbl_data_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Define Mappingset.
        /// </summary>
        internal static string lbl_define_mapping {
            get {
                return ResourceManager.GetString("lbl_define_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        internal static string lbl_delete {
            get {
                return ResourceManager.GetString("lbl_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure to Delete Datacube?.
        /// </summary>
        internal static string lbl_delete_cube_confirm {
            get {
                return ResourceManager.GetString("lbl_delete_cube_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure to Delete DSD?.
        /// </summary>
        internal static string lbl_delete_dsd_confirm {
            get {
                return ResourceManager.GetString("lbl_delete_dsd_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Mappingset.
        /// </summary>
        internal static string lbl_delete_mapping {
            get {
                return ResourceManager.GetString("lbl_delete_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure to Delete Mapping?.
        /// </summary>
        internal static string lbl_delete_mapping_confirm {
            get {
                return ResourceManager.GetString("lbl_delete_mapping_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure to Delete User?.
        /// </summary>
        internal static string lbl_delete_user_confirm {
            get {
                return ResourceManager.GetString("lbl_delete_user_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Description of Mappingset.
        /// </summary>
        internal static string lbl_desc_mapping {
            get {
                return ResourceManager.GetString("lbl_desc_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning! Max selectable dimensions:.
        /// </summary>
        internal static string lbl_dim_max {
            get {
                return ResourceManager.GetString("lbl_dim_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Domain.
        /// </summary>
        internal static string lbl_domain {
            get {
                return ResourceManager.GetString("lbl_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DSD definition avaible.
        /// </summary>
        internal static string lbl_dsd_avaible {
            get {
                return ResourceManager.GetString("lbl_dsd_avaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete DSD.
        /// </summary>
        internal static string lbl_dsd_delete {
            get {
                return ResourceManager.GetString("lbl_dsd_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import SDMX Structure.
        /// </summary>
        internal static string lbl_dsd_import {
            get {
                return ResourceManager.GetString("lbl_dsd_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Datacube avaible.
        /// </summary>
        internal static string lbl_ds_avaible {
            get {
                return ResourceManager.GetString("lbl_ds_avaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Category.
        /// </summary>
        internal static string lbl_ds_category {
            get {
                return ResourceManager.GetString("lbl_ds_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Datacube unique code.
        /// </summary>
        internal static string lbl_ds_code {
            get {
                return ResourceManager.GetString("lbl_ds_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create Datacube.
        /// </summary>
        internal static string lbl_ds_create {
            get {
                return ResourceManager.GetString("lbl_ds_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Datacube.
        /// </summary>
        internal static string lbl_ds_delete {
            get {
                return ResourceManager.GetString("lbl_ds_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Datacube info.
        /// </summary>
        internal static string lbl_ds_info {
            get {
                return ResourceManager.GetString("lbl_ds_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Datacube display names.
        /// </summary>
        internal static string lbl_ds_name {
            get {
                return ResourceManager.GetString("lbl_ds_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create new Datacube.
        /// </summary>
        internal static string lbl_ds_new {
            get {
                return ResourceManager.GetString("lbl_ds_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        internal static string lbl_edit {
            get {
                return ResourceManager.GetString("lbl_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        internal static string lbl_email {
            get {
                return ResourceManager.GetString("lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Filename.
        /// </summary>
        internal static string lbl_filename {
            get {
                return ResourceManager.GetString("lbl_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Filesize.
        /// </summary>
        internal static string lbl_filesize {
            get {
                return ResourceManager.GetString("lbl_filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First row has name of columns.
        /// </summary>
        internal static string lbl_first_row_column {
            get {
                return ResourceManager.GetString("lbl_first_row_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sample time in current format.
        /// </summary>
        internal static string lbl_format_sample {
            get {
                return ResourceManager.GetString("lbl_format_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Columns of csv data.
        /// </summary>
        internal static string lbl_headers {
            get {
                return ResourceManager.GetString("lbl_headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ID.
        /// </summary>
        internal static string lbl_id {
            get {
                return ResourceManager.GetString("lbl_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Import.
        /// </summary>
        internal static string lbl_import {
            get {
                return ResourceManager.GetString("lbl_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import SDMX Data.
        /// </summary>
        internal static string lbl_importSDMXData {
            get {
                return ResourceManager.GetString("lbl_importSDMXData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import SDMX Structure.
        /// </summary>
        internal static string lbl_importSDMXSchema {
            get {
                return ResourceManager.GetString("lbl_importSDMXSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Database Installation.
        /// </summary>
        internal static string lbl_install {
            get {
                return ResourceManager.GetString("lbl_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Install required.
        /// </summary>
        internal static string lbl_install_required {
            get {
                return ResourceManager.GetString("lbl_install_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Make in Production.
        /// </summary>
        internal static string lbl_in_production {
            get {
                return ResourceManager.GetString("lbl_in_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attribute file.
        /// </summary>
        internal static string lbl_is_attribute_file {
            get {
                return ResourceManager.GetString("lbl_is_attribute_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Loader.
        /// </summary>
        internal static string lbl_loader {
            get {
                return ResourceManager.GetString("lbl_loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send report with email.
        /// </summary>
        internal static string lbl_loader_mail_to {
            get {
                return ResourceManager.GetString("lbl_loader_mail_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select data source.
        /// </summary>
        internal static string lbl_loader_select_data {
            get {
                return ResourceManager.GetString("lbl_loader_select_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select mapping set.
        /// </summary>
        internal static string lbl_loader_select_mapping {
            get {
                return ResourceManager.GetString("lbl_loader_select_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View Map.
        /// </summary>
        internal static string lbl_loader_view_map {
            get {
                return ResourceManager.GetString("lbl_loader_view_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Completion of operation..
        /// </summary>
        internal static string lbl_loading_wait {
            get {
                return ResourceManager.GetString("lbl_loading_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        internal static string lbl_login {
            get {
                return ResourceManager.GetString("lbl_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manager Mapping Set.
        /// </summary>
        internal static string lbl_man_mappingset {
            get {
                return ResourceManager.GetString("lbl_man_mappingset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manager Profile.
        /// </summary>
        internal static string lbl_man_profile {
            get {
                return ResourceManager.GetString("lbl_man_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manager Structure.
        /// </summary>
        internal static string lbl_man_structure {
            get {
                return ResourceManager.GetString("lbl_man_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please provide a mapping for all data cube field..
        /// </summary>
        internal static string lbl_mapping_all_component {
            get {
                return ResourceManager.GetString("lbl_mapping_all_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avvaible mapping.
        /// </summary>
        internal static string lbl_mapping_avaible {
            get {
                return ResourceManager.GetString("lbl_mapping_avaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create mapping.
        /// </summary>
        internal static string lbl_mapping_create {
            get {
                return ResourceManager.GetString("lbl_mapping_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete mapping.
        /// </summary>
        internal static string lbl_mapping_delete {
            get {
                return ResourceManager.GetString("lbl_mapping_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create new mapping.
        /// </summary>
        internal static string lbl_mapping_new {
            get {
                return ResourceManager.GetString("lbl_mapping_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Has been chosen to use a transcoding time but no character is specified..
        /// </summary>
        internal static string lbl_mapping_specific_char {
            get {
                return ResourceManager.GetString("lbl_mapping_specific_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please select a valid Datacube..
        /// </summary>
        internal static string lbl_mapping_specific_dataset {
            get {
                return ResourceManager.GetString("lbl_mapping_specific_dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All data will be remove, Continue?.
        /// </summary>
        internal static string lbl_msg_alert_install {
            get {
                return ResourceManager.GetString("lbl_msg_alert_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name of Mappingset.
        /// </summary>
        internal static string lbl_name_mapping {
            get {
                return ResourceManager.GetString("lbl_name_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Mappingset.
        /// </summary>
        internal static string lbl_new_mapping {
            get {
                return ResourceManager.GetString("lbl_new_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New User.
        /// </summary>
        internal static string lbl_new_user {
            get {
                return ResourceManager.GetString("lbl_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continue.
        /// </summary>
        internal static string lbl_next_step {
            get {
                return ResourceManager.GetString("lbl_next_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a of.
        /// </summary>
        internal static string lbl_of {
            get {
                return ResourceManager.GetString("lbl_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ignore and not insert row with some key.
        /// </summary>
        internal static string lbl_opt_import_ignore {
            get {
                return ResourceManager.GetString("lbl_opt_import_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select import mode.
        /// </summary>
        internal static string lbl_opt_import_modality {
            get {
                return ResourceManager.GetString("lbl_opt_import_modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Override record with some key.
        /// </summary>
        internal static string lbl_opt_import_override {
            get {
                return ResourceManager.GetString("lbl_opt_import_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email to send report.
        /// </summary>
        internal static string lbl_opt_import_send_mail {
            get {
                return ResourceManager.GetString("lbl_opt_import_send_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove to Production.
        /// </summary>
        internal static string lbl_out_production {
            get {
                return ResourceManager.GetString("lbl_out_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile.
        /// </summary>
        internal static string lbl_page_profile {
            get {
                return ResourceManager.GetString("lbl_page_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        internal static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change password.
        /// </summary>
        internal static string lbl_password_change {
            get {
                return ResourceManager.GetString("lbl_password_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Repeat password.
        /// </summary>
        internal static string lbl_password_repeat {
            get {
                return ResourceManager.GetString("lbl_password_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preview.
        /// </summary>
        internal static string lbl_preview {
            get {
                return ResourceManager.GetString("lbl_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string lbl_prev_step {
            get {
                return ResourceManager.GetString("lbl_prev_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enabling higher.
        /// </summary>
        internal static string lbl_prouser {
            get {
                return ResourceManager.GetString("lbl_prouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Record Count: .
        /// </summary>
        internal static string lbl_record_count {
            get {
                return ResourceManager.GetString("lbl_record_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reload.
        /// </summary>
        internal static string lbl_reload {
            get {
                return ResourceManager.GetString("lbl_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continue.
        /// </summary>
        internal static string lbl_report_continue {
            get {
                return ResourceManager.GetString("lbl_report_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New record count:.
        /// </summary>
        internal static string lbl_report_count {
            get {
                return ResourceManager.GetString("lbl_report_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A email has been send to address:.
        /// </summary>
        internal static string lbl_report_email {
            get {
                return ResourceManager.GetString("lbl_report_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The following errors occurred during insertion:.
        /// </summary>
        internal static string lbl_report_error {
            get {
                return ResourceManager.GetString("lbl_report_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finish.
        /// </summary>
        internal static string lbl_report_finish {
            get {
                return ResourceManager.GetString("lbl_report_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert mode:.
        /// </summary>
        internal static string lbl_report_mode {
            get {
                return ResourceManager.GetString("lbl_report_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operation execute by:.
        /// </summary>
        internal static string lbl_report_user {
            get {
                return ResourceManager.GetString("lbl_report_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Retrive profile.
        /// </summary>
        internal static string lbl_retrive {
            get {
                return ResourceManager.GetString("lbl_retrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role.
        /// </summary>
        internal static string lbl_role {
            get {
                return ResourceManager.GetString("lbl_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save Mappingset.
        /// </summary>
        internal static string lbl_save_mapping {
            get {
                return ResourceManager.GetString("lbl_save_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Category.
        /// </summary>
        internal static string lbl_select_category {
            get {
                return ResourceManager.GetString("lbl_select_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Datacube.
        /// </summary>
        internal static string lbl_select_ds {
            get {
                return ResourceManager.GetString("lbl_select_ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select DSD.
        /// </summary>
        internal static string lbl_select_dsd {
            get {
                return ResourceManager.GetString("lbl_select_dsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select mapping.
        /// </summary>
        internal static string lbl_select_mapping {
            get {
                return ResourceManager.GetString("lbl_select_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select transcoding time.
        /// </summary>
        internal static string lbl_select_transcoding {
            get {
                return ResourceManager.GetString("lbl_select_transcoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set Domain.
        /// </summary>
        internal static string lbl_set_domain {
            get {
                return ResourceManager.GetString("lbl_set_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set in production.
        /// </summary>
        internal static string lbl_set_in_production {
            get {
                return ResourceManager.GetString("lbl_set_in_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Leave from production.
        /// </summary>
        internal static string lbl_set_out_production {
            get {
                return ResourceManager.GetString("lbl_set_out_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm and start import data.
        /// </summary>
        internal static string lbl_start_import {
            get {
                return ResourceManager.GetString("lbl_start_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A File Source will be imported into Datacube? Continue?.
        /// </summary>
        internal static string lbl_start_import_confirm {
            get {
                return ResourceManager.GetString("lbl_start_import_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Surname.
        /// </summary>
        internal static string lbl_surname {
            get {
                return ResourceManager.GetString("lbl_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Time period.
        /// </summary>
        internal static string lbl_time_period {
            get {
                return ResourceManager.GetString("lbl_time_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload.
        /// </summary>
        internal static string lbl_upload {
            get {
                return ResourceManager.GetString("lbl_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the .csv file for get header columns used in the mappingset.
        /// </summary>
        internal static string lbl_uploadCSVChoise {
            get {
                return ResourceManager.GetString("lbl_uploadCSVChoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Specify character used to separate fields in the file.
        /// </summary>
        internal static string lbl_uploadCSVSeparator {
            get {
                return ResourceManager.GetString("lbl_uploadCSVSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select file to import.
        /// </summary>
        internal static string lbl_upload_file {
            get {
                return ResourceManager.GetString("lbl_upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select file CSV.
        /// </summary>
        internal static string lbl_upload_file_csv {
            get {
                return ResourceManager.GetString("lbl_upload_file_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select files xml with SDMX Schema information.
        /// </summary>
        internal static string lbl_upload_file_xml_schema {
            get {
                return ResourceManager.GetString("lbl_upload_file_xml_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Username.
        /// </summary>
        internal static string lbl_username {
            get {
                return ResourceManager.GetString("lbl_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use SDMX-ML file.
        /// </summary>
        internal static string lbl_use_file_type {
            get {
                return ResourceManager.GetString("lbl_use_file_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Look.
        /// </summary>
        internal static string lbl_view {
            get {
                return ResourceManager.GetString("lbl_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome.
        /// </summary>
        internal static string lbl_welcome {
            get {
                return ResourceManager.GetString("lbl_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Action.
        /// </summary>
        internal static string lbl_widget_action {
            get {
                return ResourceManager.GetString("lbl_widget_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile.
        /// </summary>
        internal static string lbl_widget_profile {
            get {
                return ResourceManager.GetString("lbl_widget_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The E-mail is mandatory.
        /// </summary>
        internal static string msg_add_email {
            get {
                return ResourceManager.GetString("msg_add_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Name is mandatory.
        /// </summary>
        internal static string msg_add_name {
            get {
                return ResourceManager.GetString("msg_add_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Password is mandatory.
        /// </summary>
        internal static string msg_add_password {
            get {
                return ResourceManager.GetString("msg_add_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Surname is mandatory.
        /// </summary>
        internal static string msg_add_surname {
            get {
                return ResourceManager.GetString("msg_add_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Username is mandatory.
        /// </summary>
        internal static string msg_add_username {
            get {
                return ResourceManager.GetString("msg_add_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Databases not found.
        /// </summary>
        internal static string msg_DB_Not_Found {
            get {
                return ResourceManager.GetString("msg_DB_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dimensions selected.
        /// </summary>
        internal static string msg_dim_curr_sel {
            get {
                return ResourceManager.GetString("msg_dim_curr_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A new installation of the archives data is required by the system. Click the button to make it install itself.
        /// </summary>
        internal static string msg_install_required {
            get {
                return ResourceManager.GetString("msg_install_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome in SDMXDataloader import data interface..
        /// </summary>
        internal static string msg_loader_welcome {
            get {
                return ResourceManager.GetString("msg_loader_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please wait... Wait until the operation could take several minutes. Do not close your browser or turn off your computer..
        /// </summary>
        internal static string msg_loading_wait {
            get {
                return ResourceManager.GetString("msg_loading_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remember if you have uploaded a data file XML , mapping not is required..
        /// </summary>
        internal static string msg_mapping_a_1 {
            get {
                return ResourceManager.GetString("msg_mapping_a_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a For use the function of site, please .
        /// </summary>
        internal static string msg_needlogin {
            get {
                return ResourceManager.GetString("msg_needlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The E-mail is not valid.
        /// </summary>
        internal static string msg_not_valid_email {
            get {
                return ResourceManager.GetString("msg_not_valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passwords don&apos;t match.
        /// </summary>
        internal static string msg_password_not_match {
            get {
                return ResourceManager.GetString("msg_password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password lost?.
        /// </summary>
        internal static string msg_retrivepsw {
            get {
                return ResourceManager.GetString("msg_retrivepsw", resourceCulture);
            }
        }
    }
}
