//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Notification", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not permissed..
        /// </summary>
        internal static string err_action_denied {
            get {
                return ResourceManager.GetString("err_action_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection invalid..
        /// </summary>
        internal static string err_connection_setting {
            get {
                return ResourceManager.GetString("err_connection_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Category..
        /// </summary>
        internal static string err_cubeCategory {
            get {
                return ResourceManager.GetString("err_cubeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a unique code..
        /// </summary>
        internal static string err_cubeCode {
            get {
                return ResourceManager.GetString("err_cubeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select dimensions for new cube..
        /// </summary>
        internal static string err_cubeDimensions {
            get {
                return ResourceManager.GetString("err_cubeDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid name..
        /// </summary>
        internal static string err_cubeName {
            get {
                return ResourceManager.GetString("err_cubeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error set production status..
        /// </summary>
        internal static string err_cube_in_prod {
            get {
                return ResourceManager.GetString("err_cube_in_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error, try again..
        /// </summary>
        internal static string err_download {
            get {
                return ResourceManager.GetString("err_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacube not created..
        /// </summary>
        internal static string err_ds_create {
            get {
                return ResourceManager.GetString("err_ds_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacube non eliminato..
        /// </summary>
        internal static string err_ds_delete {
            get {
                return ResourceManager.GetString("err_ds_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacube invalid..
        /// </summary>
        internal static string err_ds_invalid {
            get {
                return ResourceManager.GetString("err_ds_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email empty..
        /// </summary>
        internal static string err_email_empty {
            get {
                return ResourceManager.GetString("err_email_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of file not support..
        /// </summary>
        internal static string err_file_bad_type {
            get {
                return ResourceManager.GetString("err_file_bad_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file CSV error..
        /// </summary>
        internal static string err_file_csv {
            get {
                return ResourceManager.GetString("err_file_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File empty..
        /// </summary>
        internal static string err_file_empty {
            get {
                return ResourceManager.GetString("err_file_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string err_file_not_found {
            get {
                return ResourceManager.GetString("err_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data fail..
        /// </summary>
        internal static string err_import_data {
            get {
                return ResourceManager.GetString("err_import_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert fail..
        /// </summary>
        internal static string err_insert {
            get {
                return ResourceManager.GetString("err_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing archives. Check the configuration files and database connections..
        /// </summary>
        internal static string err_install {
            get {
                return ResourceManager.GetString("err_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        internal static string err_login {
            get {
                return ResourceManager.GetString("err_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping not created..
        /// </summary>
        internal static string err_mapping_create {
            get {
                return ResourceManager.GetString("err_mapping_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping not deleted..
        /// </summary>
        internal static string err_mapping_delete {
            get {
                return ResourceManager.GetString("err_mapping_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password empty..
        /// </summary>
        internal static string err_password_empty {
            get {
                return ResourceManager.GetString("err_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview not permiss..
        /// </summary>
        internal static string err_preview_data {
            get {
                return ResourceManager.GetString("err_preview_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve mapping is not possible for this data source..
        /// </summary>
        internal static string err_resolve_mapping {
            get {
                return ResourceManager.GetString("err_resolve_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fauil to send email..
        /// </summary>
        internal static string err_send_email {
            get {
                return ResourceManager.GetString("err_send_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file error..
        /// </summary>
        internal static string err_upload {
            get {
                return ResourceManager.GetString("err_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username empty..
        /// </summary>
        internal static string err_username_empty {
            get {
                return ResourceManager.GetString("err_username_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered user with this email..
        /// </summary>
        internal static string err_user_email_not_found {
            get {
                return ResourceManager.GetString("err_user_email_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success set production status..
        /// </summary>
        internal static string succ_cube_in_prod {
            get {
                return ResourceManager.GetString("succ_cube_in_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataflow in production..
        /// </summary>
        internal static string succ_df_in_prod {
            get {
                return ResourceManager.GetString("succ_df_in_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataflow out production..
        /// </summary>
        internal static string succ_df_out_prod {
            get {
                return ResourceManager.GetString("succ_df_out_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacube created..
        /// </summary>
        internal static string succ_ds_create {
            get {
                return ResourceManager.GetString("succ_ds_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacube delete..
        /// </summary>
        internal static string succ_ds_delete {
            get {
                return ResourceManager.GetString("succ_ds_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacube valid..
        /// </summary>
        internal static string succ_ds_valid {
            get {
                return ResourceManager.GetString("succ_ds_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data import success..
        /// </summary>
        internal static string succ_import_data {
            get {
                return ResourceManager.GetString("succ_import_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert success..
        /// </summary>
        internal static string succ_insert {
            get {
                return ResourceManager.GetString("succ_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of the archives made. You can now log in using the login page..
        /// </summary>
        internal static string succ_install {
            get {
                return ResourceManager.GetString("succ_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping created..
        /// </summary>
        internal static string succ_mapping_create {
            get {
                return ResourceManager.GetString("succ_mapping_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping deleted..
        /// </summary>
        internal static string succ_mapping_delete {
            get {
                return ResourceManager.GetString("succ_mapping_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mail is been sended on your email address. You can found in a new password for loged in. .
        /// </summary>
        internal static string succ_retrive {
            get {
                return ResourceManager.GetString("succ_retrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file success..
        /// </summary>
        internal static string succ_upload {
            get {
                return ResourceManager.GetString("succ_upload", resourceCulture);
            }
        }
    }
}
